{
 "title": "Rippled Syncing Info",
 "description": "Rippled Node Syncing Information",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_timestamp, job)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(node_timestamp{job=\"$job\", project=~\"xrp-mainnet|xrp-testnet\"}, project)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_timestamp{job=\"$job\", project=\"$project\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rippled Load",
   "type": "timeseries",
   "description": "Rippled Load Factor and Threads\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rippled_load_factor{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Rippled Load Factor"
    },
    {
     "expr": "rippled_load_threads{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Process Threads"
    }
   ]
  },
  {
   "title": "Rippled Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rippled_peers{name=\"$node\", job=\"$job\", project=\"$project\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "rippled_peer_disconnects{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Disconnected Peers"
    }
   ]
  },
  {
   "title": "Service Data",
   "type": "timeseries",
   "description": "Service Data",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rippled_last_close_converge_times{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Last Close Time"
    },
    {
     "expr": "rippled_last_close_proposers{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Last Close Proposers"
    },
    {
     "expr": "rippled_clientrpc_in_progress{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "RPC Calls In Progress"
    }
   ]
  },
  {
   "title": "Rippled Last Block Age in Seconds",
   "type": "timeseries",
   "description": "Rippled last synced block was this seconds old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "node_timestamp{name=\"$node\", project=\"$project\", job=\"$job\"} - rippled_ledger_index_time{name=\"$node\", project=\"$project\", job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rippled Job Timers per second",
   "type": "timeseries",
   "description": "Rippled Job Timers per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rippled_untrustedvalidation_per_second{name=\"$node\", job=\"$job\", project=\"$project\"}",
     "legendFormat": "Untrusted Validations"
    },
    {
     "expr": "rippled_clientfeechange_per_second{name=\"$node\", job=\"$job\", project=\"$project\"}",
     "legendFormat": "Client Fee Change"
    },
    {
     "expr": "rippled_transaction_per_second{name=\"$node\", job=\"$job\", project=\"$project\"}",
     "legendFormat": "Transactions"
    },
    {
     "expr": "rippled_batch_per_second{name=\"$node\", project=\"$project\", job=\"$job\"}",
     "legendFormat": "Batch"
    },
    {
     "expr": "rippled_ledgerdata_per_second{job=\"$job\", name=\"$node\", project=\"$project\"}",
     "legendFormat": "Ledger Data"
    },
    {
     "expr": "rippled_ledgerdata_avg_time{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Ledger Data Avg"
    },
    {
     "expr": "rippled_advanceledger_per_second{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Advanced Ledger"
    },
    {
     "expr": "rippled_fetchtxndata_per_second{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Fetch Txn Data"
    },
    {
     "expr": "rippled_trustedvalidation_per_second{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Trusted Validations"
    },
    {
     "expr": "rippled_trustedproposal_per_second{job=\"$job\", project=\"$project\", name=\"$node\"}",
     "legendFormat": "Trusted Proposals"
    }
   ]
  },
  {
   "title": "Rippled Service Uptime",
   "type": "stat",
   "description": "Rippled Service Uptime",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rippled_service_uptime{project=\"$project\", name=\"$node\", job=\"$job\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Rippled Last Block Time",
   "type": "stat",
   "description": "Rippled Last Synced Block Table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rippled_ledger_index_time{name=\"$node\", project=\"$project\", job=\"$job\"} * 1000",
     "legendFormat": "Last Block"
    }
   ]
  },
  {
   "title": "Rippled Last Block",
   "type": "stat",
   "description": "Rippled Last Synced Block Table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rippled_ledger_index{name=\"$node\", project=\"$project\", job=\"$job\"}",
     "legendFormat": "Last Block"
    },
    {
     "expr": "rippled_catching_up{name=\"$node\", project=\"$project\", job=\"$job\"}",
     "legendFormat": "Catching Up"
    }
   ]
  },
  {
   "title": "Rippled Catching Up History",
   "type": "timeseries",
   "description": "Rippled catching up history where \n0 = fully synced\n1 = catching up",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rippled_catching_up{name=\"$node\", job=\"$job\", project=\"$project\"}"
    }
   ]
  }
 ]
}